# Generated by Django 6.0.2 on 2026-04-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('date', 'shift_type', 'department')},
        ),
    ]
